# Generated by Django 4.0.3 on 2022-03-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(max_length=500)),
                ('main_info', models.CharField(max_length=2000)),
                ('content', models.CharField(max_length=10000)),
                ('category', models.CharField(default='different', max_length=100)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
