# Generated by Django 4.0.3 on 2022-03-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
