# Generated by Django 4.0.3 on 2022-03-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_news_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='permission',
            field=models.BooleanField(default=1),
        ),
    ]
